import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:streamsize_core/streamsize_core.dart';

String buildShareText(PlanRecommendation recommendation, HouseholdScenario scenario) {
  final buffer = StringBuffer()
    ..writeln('Recommended plan: ${recommendation.downloadMbps}/${recommendation.uploadMbps} Mbps')
    ..writeln()
    ..writeln('A solid fit for most homes like yours.')
    ..writeln()
    ..writeln('Why this plan:')
    ..writeln('  • ${scenario.simultaneous4kStreams} simultaneous 4K stream(s)')
    ..writeln('  • ${scenario.devices.length} device(s) detected')
    ..writeln('  • ${scenario.cloudBackupEnabled ? 'Cloud backup headroom included' : 'No cloud backup'}')
    ..writeln()
    ..writeln('Generated by Streamsize');
  return buffer.toString();
}

Future<Uint8List> generateResultPdf(
  PlanRecommendation recommendation,
  HouseholdScenario scenario,
) async {
  final pdf = pw.Document();

  pdf.addPage(
    pw.Page(
      pageFormat: PdfPageFormat.a4,
      build: (context) {
        return pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              'Streamsize Recommendation',
              style: pw.Theme.of(context).defaultTextStyle.copyWith(
                    fontSize: 24,
                    fontWeight: pw.FontWeight.bold,
                  ),
            ),
            pw.SizedBox(height: 16),
            pw.Text(
              'Recommended plan: ${recommendation.downloadMbps}/${recommendation.uploadMbps} Mbps',
              style: pw.Theme.of(context).defaultTextStyle.copyWith(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                  ),
            ),
            pw.SizedBox(height: 8),
            pw.Text(recommendation.summary),
            pw.SizedBox(height: 16),
            pw.Text('Why this plan:', style: pw.Theme.of(context).defaultTextStyle.copyWith(fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            ...recommendation.reasons.map((r) => pw.Bullet(text: r)),
            pw.SizedBox(height: 16),
            pw.Text('Household profile:', style: pw.Theme.of(context).defaultTextStyle.copyWith(fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            pw.Bullet(text: '${scenario.simultaneous4kStreams} simultaneous 4K stream(s)'),
            pw.Bullet(text: '${scenario.simultaneousHdStreams} simultaneous HD stream(s)'),
            pw.Bullet(text: '${scenario.simultaneousVideoCalls} live video call(s)'),
            pw.Bullet(text: '${scenario.devices.length} device(s) considered'),
            pw.Bullet(text: 'Cloud backup: ${scenario.cloudBackupEnabled ? 'Yes' : 'No'}'),
            pw.SizedBox(height: 24),
            pw.Text(
              'Generated by Streamsize — https://github.com/bigwest60/streamsize',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
            ),
          ],
        );
      },
    ),
  );

  return pdf.save();
}
