import 'package:flutter_test/flutter_test.dart';
import 'package:streamsize_client/services/export_service.dart';
import 'package:streamsize_core/streamsize_core.dart';

void main() {
  final recommendation = PlanRecommendation(
    downloadMbps: 300,
    uploadMbps: 50,
    planLabel: '300/50',
    summary: 'A solid fit for most homes.',
    reasons: const ['Supports 2 4K streams', '10 devices considered'],
    confidence: ConfidenceScore.high,
  );

  final scenario = HouseholdScenario(
    homeProfile: HomeProfile.medium,
    devices: const [
      DetectedDevice(
        displayName: 'Living Room TV',
        category: DeviceCategory.tv,
        confidence: ConfidenceScore.high,
        connection: ConnectionType.wifi,
      ),
      DetectedDevice(
        displayName: 'iPhone',
        category: DeviceCategory.phone,
        confidence: ConfidenceScore.high,
        connection: ConnectionType.wifi,
      ),
    ],
    simultaneous4kStreams: 2,
    simultaneousHdStreams: 2,
    simultaneousVideoCalls: 1,
    remoteWorkers: 1,
    onlineGamers: 1,
    cloudBackupEnabled: true,
    securityCameraCount: 2,
    largeDownloadHabit: LargeDownloadHabit.weekly,
  );

  group('buildShareText', () {
    test('includes plan label', () {
      final text = buildShareText(recommendation, scenario);
      expect(text, contains('300/50'));
    });

    test('includes device count, HD stream count, and cloud backup note', () {
      final text = buildShareText(recommendation, scenario);
      expect(text, contains('2 device(s) considered'));
      expect(text, contains('2 simultaneous HD stream(s)'));
      expect(text, contains('Cloud backup headroom included'));
    });

    test('includes 4K stream count', () {
      final text = buildShareText(recommendation, scenario);
      expect(text, contains('2 simultaneous 4K stream(s)'));
    });

    test('includes attribution', () {
      final text = buildShareText(recommendation, scenario);
      expect(text, contains('Generated by Streamsize'));
    });

    test('handles no cloud backup', () {
      final noBackup = scenario.copyWith(cloudBackupEnabled: false);
      final text = buildShareText(recommendation, noBackup);
      expect(text, contains('No cloud backup'));
    });

    test('includes reasons when non-empty', () {
      final text = buildShareText(recommendation, scenario);
      expect(text, contains('Reasons:'));
      expect(text, contains('Supports 2 4K streams'));
    });
  });

  group('generateResultPdf', () {
    test('produces valid PDF bytes', () async {
      final bytes = await generateResultPdf(recommendation, scenario);
      expect(bytes.isNotEmpty, isTrue);
      // PDF header check
      expect(bytes.sublist(0, 4), equals([0x25, 0x50, 0x44, 0x46])); // %PDF
      final pdfString = String.fromCharCodes(bytes);
      // Structural markers found in every well-formed PDF
      expect(pdfString, contains('startxref'));
      expect(pdfString, contains('%%EOF'));
      expect(pdfString, contains('endobj'));
    });

    test('produces a PDF for same inputs every time', () async {
      final bytes1 = await generateResultPdf(recommendation, scenario);
      final bytes2 = await generateResultPdf(recommendation, scenario);
      // dart_pdf may embed non-deterministic metadata, so verify both are valid PDFs
      expect(bytes1.sublist(0, 4), equals([0x25, 0x50, 0x44, 0x46])); // %PDF
      expect(bytes2.sublist(0, 4), equals([0x25, 0x50, 0x44, 0x46])); // %PDF
      expect(bytes1.length, greaterThan(0));
      expect(bytes2.length, greaterThan(0));
    });
  });
}
